import 'package:flutter/material.dart';

/// Lightweight string catalogue.
///
/// We access this through `SettingsService.strings` (which owns the locale)
/// rather than a LocalizationsDelegate, because the settings layer needs to
/// drive rebuilds via [ChangeNotifier] already.
class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Qamus',
      'search_hint': 'Search any Arabic word...',
      'search_try': 'Try:',
      'or_any_word': ' or any word',
      'recent_searches': 'RECENT SEARCHES',
      'word_of_the_day': 'WORD OF THE DAY',
      'tagline_primary': 'Where Arabic Begins',
      'tagline_arabic': 'حيث تبدأ العربية',
      'clear_all': 'Clear all',
      'no_history': 'No recent searches yet',
      'no_favorites': 'No favorites yet',
      'select_language': 'Select Language',
      'results': 'Results',
      'preferences': 'Preferences',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark mode',
      'light_mode': 'Light mode',
      'interface_language': 'Interface Language',
      'arabic_font': 'Arabic Font Style',
      'show_diacritics': 'Show Diacritics',
      'diacritics_desc': 'Display vowel marks (tashkeel)',
      'audio_pronunciation': 'Audio Pronunciation',
      'audio_desc': 'Play audio automatically',
      'discover': 'Discover',
      'library': 'Library',
      'search': 'Search',
      'collections': 'Collections',
      'create_collection': 'Create Collection',
      'collection_name': 'Collection Name',
      'create': 'Create',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'remove': 'Remove',
      'add_to_collection': 'Add to Collection',
      'copied': 'Copied to clipboard',
      'no_collections': 'No collections found',
      'favorites': 'Favorites',
      'history': 'History',
      'about': 'About',
      'source_all': 'All',
      'source_muashiroh': 'Modern',
      'source_wasith': 'Wasith',
      'source_lisan': 'Lisan Al-Arab',
      'source_quran': 'Quran',
      'desc_quran': 'Words from the Holy Quran',
      'desc_lisan': 'Classical Arabic Lexicon',
      'desc_muashiroh': 'Modern Contemporary Arabic',
      'desc_wasith': 'Intermediate Dictionary',
      'desc_muhith': 'Comprehensive Dictionary',
      'desc_shihah': 'The Correct Language',
      'desc_ghoni': 'Rich Vocabulary',
      'ai_source': 'AI Generated',
      'no_collections_found': 'No collections found',
      'delete_collection': 'Delete Collection',
      'delete_collection_confirm':
          'Are you sure you want to delete this collection?',
      'added_to_collection': 'Added to',
      'no_words_collection': 'No words in this collection yet',
      'developer': 'Developer',
      'developer_name': 'Hashim Hameem',
      'visit_website': 'Visit Website',
      'no_results': 'No results found',
      'ai_offline_banner': 'Couldn\'t reach the AI dictionary. Check your connection and retry.',
      'retry': 'Retry',
      'reading_size': 'Reading size',
      'reading_size_desc': 'Scale definition text up or down',
    },
    'ur': {
      'app_title': 'قاموس',
      'search_hint': 'کوئی بھی عربی لفظ تلاش کریں...',
      'search_try': 'کوشش کریں:',
      'or_any_word': ' یا کوئی بھی لفظ',
      'recent_searches': 'حالیہ تلاش',
      'word_of_the_day': 'آج کا لفظ',
      'tagline_primary': 'جہاں عربی شروع ہوتی ہے',
      'tagline_arabic': 'حيث تبدأ العربية',
      'clear_all': 'سب صاف کریں',
      'no_history': 'ابھی کوئی حالیہ تلاش نہیں',
      'no_favorites': 'ابھی کوئی پسندیدہ نہیں',
      'select_language': 'زبان منتخب کریں',
      'results': 'نتائج',
      'preferences': 'ترجیحات',
      'settings': 'ترتیبات',
      'appearance': 'ظاہری شکل',
      'dark_mode': 'ڈارک موڈ',
      'light_mode': 'لائٹ موڈ',
      'interface_language': 'انٹرفیس کی زبان',
      'arabic_font': 'عربی فونٹ اسٹائل',
      'show_diacritics': 'اعراب دکھائیں',
      'diacritics_desc': 'زبر زیر پیش دکھائیں',
      'audio_pronunciation': 'آڈیو تلفظ',
      'audio_desc': 'خودکار طور پر آڈیو چلائیں',
      'discover': 'دریافت',
      'library': 'لائبریری',
      'search': 'تلاش',
      'collections': 'مجموعے',
      'create_collection': 'نیا مجموعہ بنائیں',
      'collection_name': 'مجموعہ کا نام',
      'create': 'بنائیں',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'remove': 'ہٹائیں',
      'add_to_collection': 'مجموعہ میں شامل کریں',
      'copied': 'کلپ بورڈ پر کاپی ہو گیا',
      'no_collections': 'کوئی مجموعہ نہیں ملا',
      'favorites': 'پسندیدہ',
      'history': 'تاریخچہ',
      'about': 'کے بارے میں',
      'source_all': 'سب',
      'source_muashiroh': 'معاصرة',
      'source_wasith': 'وسیط',
      'source_lisan': 'لسان العرب',
      'source_quran': 'قرآن',
      'desc_quran': 'قرآن پاک کے الفاظ',
      'desc_lisan': 'کلاسیکی عربی لغت',
      'desc_muashiroh': 'جدید معاصر عربی',
      'desc_wasith': 'درمیانی لغت',
      'desc_muhith': 'جامع لغت',
      'desc_shihah': 'صحیح زبان',
      'desc_ghoni': 'امیر ذخیرہ الفاظ',
      'ai_source': 'AI تولید شدہ',
      'no_collections_found': 'کوئی مجموعہ نہیں ملا',
      'delete_collection': 'مجموعہ حذف کریں',
      'delete_collection_confirm': 'کیا آپ واقعی یہ مجموعہ حذف کرنا چاہتے ہیں؟',
      'added_to_collection': 'میں شامل ہو گیا',
      'no_words_collection': 'ابھی اس مجموعے میں کوئی لفظ نہیں ہے',
      'developer': 'ڈویلپر',
      'developer_name': 'ہاشم حمیم',
      'visit_website': 'ویب سائٹ دیکھیں',
      'no_results': 'کوئی نتیجہ نہیں ملا',
      'ai_offline_banner': 'AI ڈکشنری تک رسائی ممکن نہیں۔ اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔',
      'retry': 'دوبارہ کوشش کریں',
      'reading_size': 'مطالعہ سائز',
      'reading_size_desc': 'تعریف کے متن کو بڑا یا چھوٹا کریں',
    },
    'ar': {
      'app_title': 'القاموس',
      'search_hint': 'ابحث عن أي كلمة عربية...',
      'search_try': 'جرب:',
      'or_any_word': ' أو أي كلمة',
      'recent_searches': 'عمليات البحث الأخيرة',
      'word_of_the_day': 'كلمة اليوم',
      'tagline_primary': 'حيث تبدأ العربية',
      'tagline_arabic': 'حيث تبدأ العربية',
      'clear_all': 'مسح الكل',
      'no_history': 'لا توجد عمليات بحث حديثة',
      'no_favorites': 'لا توجد عناصر مفضلة بعد',
      'select_language': 'اختر اللغة',
      'results': 'النتائج',
      'preferences': 'التفضيلات',
      'settings': 'الإعدادات',
      'appearance': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'interface_language': 'لغة الواجهة',
      'arabic_font': 'خط العربي',
      'show_diacritics': 'إظهار التشكيل',
      'diacritics_desc': 'عرض الحركات والتشكيل',
      'audio_pronunciation': 'النطق الصوتي',
      'audio_desc': 'تشغيل الصوت تلقائياً',
      'discover': 'اكتشف',
      'library': 'المكتبة',
      'search': 'بحث',
      'collections': 'المجموعات',
      'create_collection': 'إنشاء مجموعة',
      'collection_name': 'اسم المجموعة',
      'create': 'إنشاء',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'remove': 'إزالة',
      'add_to_collection': 'إضافة إلى مجموعة',
      'copied': 'تم النسخ إلى الحافظة',
      'no_collections': 'لا توجد مجموعات',
      'favorites': 'المفضلة',
      'history': 'السجل',
      'about': 'حول',
      'source_all': 'الكل',
      'source_muashiroh': 'المعاصرة',
      'source_wasith': 'الوسيط',
      'source_lisan': 'لسان العرب',
      'source_quran': 'القرآن',
      'desc_quran': 'كلمات من القرآن الكريم',
      'desc_lisan': 'معجم اللغة العربية الفصحى',
      'desc_muashiroh': 'اللغة العربية المعاصرة الحديثة',
      'desc_wasith': 'المعجم الوسيط',
      'desc_muhith': 'المعجم المحيط',
      'desc_shihah': 'الصحاح',
      'desc_ghoni': 'المغني',
      'ai_source': 'مولد بالذكاء الاصطناعي',
      'no_collections_found': 'لا توجد مجموعات',
      'delete_collection': 'حذف المجموعة',
      'delete_collection_confirm': 'هل أنت متأكد من حذف هذه المجموعة؟',
      'added_to_collection': 'تمت الإضافة إلى',
      'no_words_collection': 'لا توجد كلمات في هذه المجموعة بعد',
      'developer': 'المطور',
      'developer_name': 'هاشم حميم',
      'visit_website': 'زيارة الموقع',
      'no_results': 'لا توجد نتائج',
      'ai_offline_banner': 'تعذر الوصول إلى قاموس الذكاء الاصطناعي. تحقق من اتصالك وحاول مجدداً.',
      'retry': 'إعادة المحاولة',
      'reading_size': 'حجم القراءة',
      'reading_size_desc': 'تكبير أو تصغير نص التعريفات',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }
}
