import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Qamus',
      'search_hint': 'Search any Arabic word...',
      'search_try': 'Try:',
      'or_any_word': ' or any word',
      'recent_searches': 'RECENT SEARCHES',
      'word_of_the_day': 'WORD OF THE DAY',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark mode',
      'light_mode': 'Light mode',
      'interface_language': 'Interface Language',
      'arabic_font': 'Arabic Font Style',
      'show_diacritics': 'Show Diacritics',
      'diacritics_desc': 'Display vowel marks (tashkeel)',
      'audio_pronunciation': 'Audio Pronunciation',
      'audio_desc': 'Play audio automatically',
      'discover': 'Discover',
      'library': 'Library',
      'search': 'Search',
      'collections': 'Collections',
      'create_collection': 'Create Collection',
      'collection_name': 'Collection Name',
      'create': 'Create',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'remove': 'Remove',
      'add_to_collection': 'Add to Collection',
      'copied': 'Copied to clipboard',
      'no_collections': 'No collections found',
      'favorites': 'Favorites',
      'history': 'History',
      'about': 'About',
      'source_all': 'All',
      'source_muashiroh': 'Modern',
      'source_wasith': 'Wasith',
      'source_lisan': 'Lisan Al-Arab',
      'source_quran': 'Quran',
      'desc_quran': 'Words from the Holy Quran',
      'desc_lisan': 'Classical Arabic Lexicon',
      'desc_muashiroh': 'Modern Contemporary Arabic',
      'desc_wasith': 'Intermediate Dictionary',
      'desc_muhith': 'Comprehensive Dictionary',
      'desc_shihah': 'The Correct Language',
      'desc_ghoni': 'Rich Vocabulary',
      'ai_source': 'AI Generated',
      'no_collections_found': 'No collections found',
      'delete_collection': 'Delete Collection',
      'delete_collection_confirm':
          'Are you sure you want to delete this collection?',
      'added_to_collection': 'Added to',
      'no_words_collection': 'No words in this collection yet',
      'developer': 'Developer',
      'developer_name': 'Hashim Hameem',
      'visit_website': 'Visit Website',
    },
    'ur': {
      'app_title': 'قاموس',
      'search_hint': 'کوئی بھی عربی لفظ تلاش کریں...',
      'search_try': 'کوشش کریں:',
      'or_any_word': ' یا کوئی بھی لفظ',
      'recent_searches': 'حالیہ تلاش',
      'word_of_the_day': 'آج کا لفظ',
      'settings': 'ترتیبات',
      'appearance': 'ظاہری شکل',
      'dark_mode': 'ڈارک موڈ',
      'light_mode': 'لائٹ موڈ',
      'interface_language': 'انٹرفیس کی زبان',
      'arabic_font': 'عربی فونٹ اسٹائل',
      'show_diacritics': 'اعراب دکھائیں',
      'diacritics_desc': 'زبر زیر پیش دکھائیں',
      'audio_pronunciation': 'آڈیو تلفظ',
      'audio_desc': 'خودکار طور پر آڈیو چلائیں',
      'discover': 'دریافت',
      'library': 'لائبریری',
      'search': 'تلاش',
      'collections': 'مجموعے',
      'create_collection': 'نیا مجموعہ بنائیں',
      'collection_name': 'مجموعہ کا نام',
      'create': 'بنائیں',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'remove': 'ہٹائیں',
      'add_to_collection': 'مجموعہ میں شامل کریں',
      'copied': 'کلپ بورڈ پر کاپی ہو گیا',
      'no_collections': 'کوئی مجموعہ نہیں ملا',
      'favorites': 'پسندیدہ',
      'history': 'تاریخچہ',
      'about': 'کے بارے میں',
      'source_all': 'سب',
      'source_muashiroh': 'معاصرة',
      'source_wasith': 'وسیط',
      'source_lisan': 'لسان العرب',
      'source_quran': 'قرآن',
      'desc_quran': 'قرآن پاک کے الفاظ',
      'desc_lisan': 'کلاسیکی عربی لغت',
      'desc_muashiroh': 'جدید معاصر عربی',
      'desc_wasith': 'درمیانی لغت',
      'desc_muhith': 'جامع لغت',
      'desc_shihah': 'صحیح زبان',
      'desc_ghoni': 'امیر ذخیرہ الفاظ',
      'ai_source': 'AI تولید شدہ',
      'no_collections_found': 'کوئی مجموعہ نہیں ملا',
      'delete_collection': 'مجموعہ حذف کریں',
      'delete_collection_confirm': 'کیا آپ واقعی یہ مجموعہ حذف کرنا چاہتے ہیں؟',
      'added_to_collection': 'میں شامل ہو گیا',
      'no_words_collection': 'ابھی اس مجموعے میں کوئی لفظ نہیں ہے',
      'developer': 'ڈویلپر',
      'developer_name': 'ہاشم حمیم',
      'visit_website': 'ویب سائٹ دیکھیں',
    },
    'ar': {
      'app_title': 'القاموس',
      'search_hint': 'ابحث عن أي كلمة عربية...',
      'search_try': 'جرب:',
      'or_any_word': ' أو أي كلمة',
      'recent_searches': 'عمليات البحث الأخيرة',
      'word_of_the_day': 'كلمة اليوم',
      'settings': 'الإعدادات',
      'appearance': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'interface_language': 'لغة الواجهة',
      'arabic_font': 'خط العربي',
      'show_diacritics': 'إظهار التشكيل',
      'diacritics_desc': 'عرض الحركات والتشكيل',
      'audio_pronunciation': 'النطق الصوتي',
      'audio_desc': 'تشغيل الصوت تلقائياً',
      'discover': 'اكتشف',
      'library': 'المكتبة',
      'search': 'بحث',
      'collections': 'المجموعات',
      'create_collection': 'إنشاء مجموعة',
      'collection_name': 'اسم المجموعة',
      'create': 'إنشاء',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'remove': 'إزالة',
      'add_to_collection': 'إضافة إلى مجموعة',
      'copied': 'تم النسخ إلى الحافظة',
      'no_collections': 'لا توجد مجموعات',
      'favorites': 'المفضلة',
      'history': 'السجل',
      'about': 'حول',
      'source_all': 'الكل',
      'source_muashiroh': 'المعاصرة',
      'source_wasith': 'الوسيط',
      'source_lisan': 'لسان العرب',
      'source_quran': 'القرآن',
      'desc_quran': 'كلمات من القرآن الكريم',
      'desc_lisan': 'معجم اللغة العربية الفصحى',
      'desc_muashiroh': 'اللغة العربية المعاصرة الحديثة',
      'desc_wasith': 'المعجم الوسيط',
      'desc_muhith': 'المعجم المحيط',
      'desc_shihah': 'الصحاح',
      'desc_ghoni': 'المغني',
      'ai_source': 'مولد بالذكاء الاصطناعي',
      'no_collections_found': 'لا توجد مجموعات',
      'delete_collection': 'حذف المجموعة',
      'delete_collection_confirm': 'هل أنت متأكد من حذف هذه المجموعة؟',
      'added_to_collection': 'تمت الإضافة إلى',
      'no_words_collection': 'لا توجد كلمات في هذه المجموعة بعد',
      'developer': 'المطور',
      'developer_name': 'هاشم حميم',
      'visit_website': 'زيارة الموقع',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static AppLocalizations of(BuildContext context) {
    // Simple implementation without LocalizationsDelegate for now
    // In a real app, we'd use Localizations.of<AppLocalizations>(context, AppLocalizations)
    // But since we are managing state manually in SettingsService, we can just access it from there
    // or pass the locale down.
    // For this architecture, we'll rely on the provider to rebuild widgets with the correct text.
    throw UnimplementedError('Use SettingsService to get current locale');
  }
}
